sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '4.0'
before_install:
  - npm install -g npm@latest-2
  - npm --version

